package com.app.aplication.inventoryprojectamovil.models;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.app.aplication.inventoryprojectamovil.models.Inventory;
import com.app.aplication.inventoryprojectamovil.models.Product;

import com.app.aplication.inventoryprojectamovil.models.InventoryDao;
import com.app.aplication.inventoryprojectamovil.models.ProductDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig inventoryDaoConfig;
    private final DaoConfig productDaoConfig;

    private final InventoryDao inventoryDao;
    private final ProductDao productDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        inventoryDaoConfig = daoConfigMap.get(InventoryDao.class).clone();
        inventoryDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        inventoryDao = new InventoryDao(inventoryDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);

        registerDao(Inventory.class, inventoryDao);
        registerDao(Product.class, productDao);
    }
    
    public void clear() {
        inventoryDaoConfig.getIdentityScope().clear();
        productDaoConfig.getIdentityScope().clear();
    }

    public InventoryDao getInventoryDao() {
        return inventoryDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

}
